# Numpy - O3
By. Malya Maritza

## Latihan Soal

* SOAL KE - 1

In [5]:
import numpy as num

a = num.full((5,5), 5)
a[1:4, 1:4] = 0
a[2, 2] = 9

print(a)

[[5 5 5 5 5]
 [5 0 0 0 5]
 [5 0 9 0 5]
 [5 0 0 0 5]
 [5 5 5 5 5]]


* SOAL KE - 2

In [10]:
b = num.full((7, 7), 8)
b[1:6, 0] = 6
b[1:6, 6] = 6
b[1:6, 1:6] = 0

print(b)

[[8 8 8 8 8 8 8]
 [6 0 0 0 0 0 6]
 [6 0 0 0 0 0 6]
 [6 0 0 0 0 0 6]
 [6 0 0 0 0 0 6]
 [6 0 0 0 0 0 6]
 [8 8 8 8 8 8 8]]


* SOAL KE - 3

In [15]:
c = num.full((8, 8), 7)
c[1:7, 1:7] = 0
c[2:6, 2:6] = 6 
c[3:5, 3:5] = 0

print(c)

[[7 7 7 7 7 7 7 7]
 [7 0 0 0 0 0 0 7]
 [7 0 6 6 6 6 0 7]
 [7 0 6 0 0 6 0 7]
 [7 0 6 0 0 6 0 7]
 [7 0 6 6 6 6 0 7]
 [7 0 0 0 0 0 0 7]
 [7 7 7 7 7 7 7 7]]
